#theme: jekyll-theme-primer
remote_theme: ignoredambience/tc39-website@repo-as-jekyll-theme

plugins:
  - jekyll-sitemap

collections:
  bugzilla:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "bugzilla"
    values:
      layout: "bugzilla"
